"""One source, several installs (ROADMAP Phase 6).

The six skills plus the shared documents are the real product; the CLI is
scaffolding around them. This module turns that one source into the versioned
artifacts each distribution channel wants:

* ``tar``           — ``memoir-skills-<version>.tar.gz`` with a MANIFEST.json
                      carrying the version and a sha256 per file, so a bundle
                      can be verified after it travels.
* ``claude-plugin`` — a Claude Code plugin tree (``.claude-plugin/plugin.json``
                      plus ``skills/``) and a marketplace entry.
* ``openclaw``      — the plain skills layout the OpenClaw adapter installs,
                      ready to drop into a workspace's ``skills/``.

Every format is generated from the same staged bundle, so they cannot drift
apart. The version comes from ``memoir_cli.__version__`` — one number for the
package, the bundle and the changelog.
"""

from __future__ import annotations

import hashlib
import json
import shutil
import tarfile
from dataclasses import dataclass
from pathlib import Path

from . import __version__
from .contract import SHARED_DOCS, SKILL_DIRS

FORMATS = ("tar", "claude-plugin", "openclaw")

PLUGIN_NAME = "memoir-agent"
PLUGIN_DESCRIPTION = (
    "A self-driving, caring memoir-writing agent: recall, structure, drafting, "
    "revision, plus an orchestrator and coach that keep the book moving."
)
AUTHOR = "Cretu and Memoir Agent Skills contributors"
HOMEPAGE = "https://github.com/Cretu/Memoir-Agent-Skills"


@dataclass
class BundleResult:
    format: str
    path: Path
    version: str
    file_count: int


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()


def _collect(source: Path) -> list[Path]:
    """Every file that belongs in a bundle, as paths relative to `source`."""
    files: list[Path] = []
    for name in SKILL_DIRS:
        root = source / name
        if not root.is_dir():
            raise SystemExit(f"skill missing from source bundle: {name}")
        files += sorted(
            p.relative_to(source) for p in root.rglob("*") if p.is_file()
        )
    for rel in SHARED_DOCS:
        if not (source / rel).is_file():
            raise SystemExit(f"shared document missing from source bundle: {rel}")
        files.append(Path(rel))
    return files


MANIFEST_NAME = "MANIFEST.json"


def write_manifest(root: Path, version: str) -> int:
    """Describe what was actually built.

    The manifest is generated by walking the finished tree rather than from the
    source list, so it can never disagree with the layout a format chose (an
    earlier version hashed source-relative paths and could not verify a bundle
    that nested its skills under `skills/`).
    """
    files = sorted(
        p for p in root.rglob("*") if p.is_file() and p.name != MANIFEST_NAME
    )
    data = {
        "name": PLUGIN_NAME,
        "version": version,
        "description": PLUGIN_DESCRIPTION,
        "homepage": HOMEPAGE,
        "skills": list(SKILL_DIRS),
        "shared_documents": list(SHARED_DOCS),
        "files": {
            p.relative_to(root).as_posix(): _sha256(p) for p in files
        },
    }
    (root / MANIFEST_NAME).write_text(
        json.dumps(data, indent=2) + "\n", encoding="utf-8"
    )
    return len(files)


def _copy_skills(source: Path, dest: Path) -> int:
    """Copy the six skill directories (not the shared documents)."""
    dest.mkdir(parents=True, exist_ok=True)
    count = 0
    for name in SKILL_DIRS:
        root = source / name
        if not root.is_dir():
            raise SystemExit(f"skill missing from source bundle: {name}")
        for src in sorted(p for p in root.rglob("*") if p.is_file()):
            target = dest / src.relative_to(source)
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, target)
            count += 1
    return count


def _copy_shared(source: Path, dest: Path) -> int:
    dest.mkdir(parents=True, exist_ok=True)
    for rel in SHARED_DOCS:
        if not (source / rel).is_file():
            raise SystemExit(f"shared document missing from source bundle: {rel}")
        shutil.copy2(source / rel, dest / Path(rel).name)
    return len(SHARED_DOCS)


def _copy_tree(source: Path, dest: Path) -> int:
    return _copy_skills(source, dest) + _copy_shared(source, dest)


def build_tar(source: Path, out_dir: Path, version: str) -> BundleResult:
    out_dir.mkdir(parents=True, exist_ok=True)
    stage = out_dir / f"memoir-skills-{version}"
    if stage.exists():
        shutil.rmtree(stage)
    _copy_tree(source, stage)
    count = write_manifest(stage, version)
    archive = out_dir / f"memoir-skills-{version}.tar.gz"
    if archive.exists():
        archive.unlink()
    with tarfile.open(archive, "w:gz") as tar:
        tar.add(stage, arcname=stage.name)
    shutil.rmtree(stage)
    return BundleResult("tar", archive, version, count + 1)


def build_claude_plugin(source: Path, out_dir: Path, version: str) -> BundleResult:
    """A Claude Code plugin tree plus a single-plugin marketplace entry.

    Validate with the local Claude Code tooling before publishing — this writes
    the layout, it cannot check it against the live plugin schema.
    """
    root = out_dir / PLUGIN_NAME
    if root.exists():
        shutil.rmtree(root)
    (root / ".claude-plugin").mkdir(parents=True)

    _copy_skills(source, root / "skills")
    # The skills reference the shared documents by bare filename; one copy at
    # the plugin root keeps the plugin self-contained without duplicating them.
    _copy_shared(source, root)

    (root / ".claude-plugin" / "plugin.json").write_text(
        json.dumps(
            {
                "name": PLUGIN_NAME,
                "description": PLUGIN_DESCRIPTION,
                "version": version,
                "author": {"name": AUTHOR},
                "homepage": HOMEPAGE,
                "license": "MIT",
                "keywords": ["memoir", "writing", "life-story", "biography"],
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    (root / ".claude-plugin" / "marketplace.json").write_text(
        json.dumps(
            {
                "name": "memoir-agent-skills",
                "owner": {"name": AUTHOR, "url": HOMEPAGE},
                "plugins": [
                    {
                        "name": PLUGIN_NAME,
                        "source": f"./{PLUGIN_NAME}",
                        "description": PLUGIN_DESCRIPTION,
                        "version": version,
                    }
                ],
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    (root / "README.md").write_text(
        f"# {PLUGIN_NAME} {version}\n\n{PLUGIN_DESCRIPTION}\n\n"
        f"Generated by `memoir bundle --format claude-plugin`. Source: {HOMEPAGE}\n\n"
        "The skills expect a workspace with `memories/` and `chapters/`; create one\n"
        "with `memoir init --workspace <path>` (or by hand — see the source repo).\n",
        encoding="utf-8",
    )
    count = write_manifest(root, version)
    return BundleResult("claude-plugin", root, version, count)


def build_openclaw(source: Path, out_dir: Path, version: str) -> BundleResult:
    """The plain skills layout the OpenClaw adapter installs."""
    root = out_dir / f"memoir-openclaw-{version}"
    if root.exists():
        shutil.rmtree(root)
    _copy_tree(source, root / "skills")
    (root / "README.md").write_text(
        f"# memoir skills for OpenClaw ({version})\n\n"
        "Copy `skills/` into your OpenClaw workspace, then register the proactive\n"
        "jobs (`memoir schedule --adapter openclaw` emits the `openclaw cron create`\n"
        f"commands). Source: {HOMEPAGE}\n",
        encoding="utf-8",
    )
    count = write_manifest(root, version)
    return BundleResult("openclaw", root, version, count)


BUILDERS = {
    "tar": build_tar,
    "claude-plugin": build_claude_plugin,
    "openclaw": build_openclaw,
}


def build(source: Path, out_dir: Path, fmt: str, version: str = "") -> BundleResult:
    if fmt not in FORMATS:
        raise SystemExit(f"unknown format {fmt!r}; choose from {', '.join(FORMATS)}")
    out_dir.mkdir(parents=True, exist_ok=True)
    return BUILDERS[fmt](source, out_dir, version or __version__)


def verify(archive_or_dir: Path) -> tuple[bool, list[str]]:
    """Re-check a built bundle against its MANIFEST.json checksums."""
    root = archive_or_dir
    if root.is_file():
        raise SystemExit("verify expects an unpacked bundle directory")
    manifest_path = root / MANIFEST_NAME
    if not manifest_path.is_file():
        raise SystemExit(f"no MANIFEST.json in {root}")
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    problems = []
    for rel, expected in data.get("files", {}).items():
        path = root / rel
        if not path.is_file():
            problems.append(f"missing: {rel}")
        elif _sha256(path) != expected:
            problems.append(f"checksum mismatch: {rel}")
    return (not problems), problems
