"""C4 — outbound notification. Generates <ws>/.memoir/notify.sh + a secrets env file.

Secrets never go into the script (which may end up in dotfile backups); they go
into .memoir/notify.env with mode 0600, sourced at runtime. The channel is for
nudges — never manuscript content (see SECURITY.md).
"""

from __future__ import annotations

import os
from pathlib import Path

from .contract import memoir_dir

PROVIDERS = ("ntfy", "telegram", "slack", "file")

_SCRIPT_HEADER = """#!/bin/sh
# memoir notify (C4) — reads the message on stdin, delivers to the writer.
# Generated by `memoir schedule`; secrets live in notify.env (0600).
set -u
DIR="$(dirname "$0")"
[ -f "$DIR/notify.env" ] && . "$DIR/notify.env"
MSG="$(cat)"
[ -n "$MSG" ] || exit 0
"""

_BODIES = {
    "ntfy": """exec curl -fsS -d "$MSG" "https://ntfy.sh/$MEMOIR_NTFY_TOPIC" >/dev/null
""",
    "telegram": """exec curl -fsS "https://api.telegram.org/bot$MEMOIR_TG_TOKEN/sendMessage" \\
  --data-urlencode "chat_id=$MEMOIR_TG_CHAT" --data-urlencode "text=$MSG" >/dev/null
""",
    "slack": """payload=$(printf '{"text":"%s"}' "$(printf '%s' "$MSG" | sed 's/"/\\\\"/g')")
exec curl -fsS -X POST -H 'Content-type: application/json' -d "$payload" "$MEMOIR_SLACK_WEBHOOK" >/dev/null
""",
    "file": """printf '%s\\n---\\n' "$MSG" >> "$DIR/nudges.log"
""",
}


def _env_lines(provider: str, opts: dict) -> list[str]:
    if provider == "ntfy":
        return [f"MEMOIR_NTFY_TOPIC={opts['ntfy_topic']}"]
    if provider == "telegram":
        return [
            f"MEMOIR_TG_TOKEN={opts['telegram_token']}",
            f"MEMOIR_TG_CHAT={opts['telegram_chat']}",
        ]
    if provider == "slack":
        return [f"MEMOIR_SLACK_WEBHOOK={opts['slack_webhook']}"]
    return []


def required_opts(provider: str) -> list[str]:
    return {
        "ntfy": ["ntfy_topic"],
        "telegram": ["telegram_token", "telegram_chat"],
        "slack": ["slack_webhook"],
        "file": [],
    }[provider]


def write_notifier(workspace: Path, provider: str, opts: dict) -> Path:
    """Write notify.sh (+ notify.env for secret-bearing providers)."""
    if provider not in PROVIDERS:
        raise ValueError(f"unknown provider {provider!r}; choose from {PROVIDERS}")
    missing = [k for k in required_opts(provider) if not opts.get(k)]
    if missing:
        raise ValueError(
            f"provider {provider!r} needs: " + ", ".join(f"--{m.replace('_', '-')}" for m in missing)
        )

    d = memoir_dir(workspace)
    script = d / "notify.sh"
    script.write_text(_SCRIPT_HEADER + _BODIES[provider], encoding="utf-8")
    os.chmod(script, 0o700)

    env_lines = _env_lines(provider, opts)
    env_file = d / "notify.env"
    if env_lines:
        env_file.write_text("\n".join(env_lines) + "\n", encoding="utf-8")
        os.chmod(env_file, 0o600)
    elif env_file.exists():
        env_file.unlink()
    return script
